
name: Reddit Post Translation Cron Job

on:
  schedule:
    # 5분마다 실행
    - cron: '*/5 * * * *'

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call API to translate Reddit posts
        run: |
          curl -X GET "https://reddit-umber.vercel.app//api/reddit-task" 
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"
